CREATE TABLE IF NOT EXISTS users (
    email VARCHAR(255) NOT NULL,
    pass VARCHAR(60) NOT NULL,
    UNIQUE(email)
);

CREATE TABLE IF NOT EXISTS kmom (
    kmom SMALLINT NOT NULL,
    kmomtext VARCHAR NOT NULL,
    UNIQUE(kmom)
);

CREATE TABLE IF NOT EXISTS texts (
    nr SMALLINT NOT NULL,
    texts VARCHAR NOT NULL,
    UNIQUE(nr)
);
